apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: m-ecommerce
  labels:
    app: product-service
spec:
  selector:
    app: product-deployment
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001