apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  namespace: m-ecommerce
spec:
  selector:
    matchLabels:
      app: product-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: product-deployment
    spec:
      containers:
          - name: product-deployment
            image: asmaeel/product-microservice:1.4
            ports:
              - containerPort: 5001
                name: product-port
            livenessProbe:
              httpGet:
                port: product-port
                path: /health
              failureThreshold: 1
              periodSeconds: 10
            startupProbe:
              httpGet:
                port: product-port
                path: /health
              failureThreshold: 30
              periodSeconds: 10
            readinessProbe:
              httpGet:
                port: product-port
                path: /ready
              failureThreshold: 1
              periodSeconds: 10
            env:
              - name: DB_HOST
                valueFrom:
                  configMapKeyRef:
                  name: mongodb-conf
                  key: host


        
